version: 2
jobs:
  build:
    docker:
      - image: ishiko/gcc-ishiko-cpp-build-prerequisites:0.7.0
    steps:
      - run: 
          name: "Set ISHIKO_CPP_ROOT environment variable and create workspace directory"
          command: mkdir -p /workspace/projects/ishiko/cpp && echo 'export ISHIKO_CPP_ROOT="/workspace/projects/ishiko/cpp"' >> $BASH_ENV
      - run:
          name: "Install build dependency: Ishiko/C++ BasePlatform"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/base-platform.git && cd base-platform/build-files/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ Errors"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/errors.git && cd errors/build-files/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ Memory"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/memory.git && cd memory/build-files/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ Types"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/types.git && cd types/build-files/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ Collections"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/collections.git && cd collections/build-files/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ Time"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/time.git && cd time/build-files/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ Text"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/text.git && cd text/build-files/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ Process"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/process.git && cd process/build-files/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ IO"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/io.git && cd io/build-files/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ FileSystem"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/filesystem.git && cd filesystem/build-files/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ XML"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/xml.git && cd xml/build-files/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ Diff"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/diff.git && cd diff/build-files/gnumake && make
      - run:
          name: "Install build dependency: Ishiko/C++ Configuration"
          command: cd /workspace/projects/ishiko/cpp && git clone https://github.com/ishiko-cpp/configuration.git && cd configuration/build-files/gnumake && make
      - checkout:
          path: /workspace/projects/ishiko/cpp/test-framework
      - run:
          name: "Build TestFramework/Core"
          command: cd /workspace/projects/ishiko/cpp/test-framework/core/build-files/gnumake && make
      - run:
          name: Test build
          command: cd /workspace/projects/ishiko/cpp/test-framework/core/tests/build-files/gnumake && make
      - run:
          name: Build ExitCodeTestHelper
          command: cd /workspace/projects/ishiko/cpp/test-framework/core/tests/exitcodetesthelper/build/gnumake && make
      - run:
          name: Build PermanentAppTestHelper
          command: cd /workspace/projects/ishiko/cpp/test-framework/core/tests/permanentapptesthelper/build/gnumake && make
      - run:
          name: Build StandardOutputTestHelper
          command: cd /workspace/projects/ishiko/cpp/test-framework/core/tests/standardoutputtesthelper/build/gnumake && make
      - run:
          name: Build WriteFileTestHelper
          command: cd /workspace/projects/ishiko/cpp/test-framework/core/tests/writefiletesthelper/build/gnumake && make
      - run:
          name: Run the tests
          command: cd /workspace/projects/ishiko/cpp/test-framework/core/tests/build-files/gnumake && ./IshikoTestFrameworkCoreTests --junit-xml-test-report=/build/test-results/IshikoTestFrameworkCore.xml
      - store_artifacts:
          path: /build/test-results/IshikoTestFrameworkCore.xml
          destination: IshikoTestFrameworkCore-test-results.xml
      - store_test_results:
          path: /build/test-results/IshikoTestFrameworkCore.xml
      - run:
          name: "Build tests"
          command: cd /workspace/projects/ishiko/cpp/test-framework/build-files/gnumake && make
      - run:
          name: "Build IshikoTestFrameworkBasicChecks example"
          command: cd /workspace/projects/ishiko/cpp/test-framework/examples/basic-checks/build/gnumake && make
      - run:
          name: "Build IshikoTestFrameworkFileComparisonChecks example"
          command: cd /workspace/projects/ishiko/cpp/test-framework/examples/file-comparison-checks/build/gnumake && make
workflows:
  version: 2
  continuous_build:
    jobs:
      - build
  weekly_build:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
